services:
  app-sample:
    build: .
    environment:
      - NODE_ENV=production
      - DEPLOYMENT=${DEPLOYMENT}
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.app-sample.rule: "Host(`app.bluegreen.duckdns.org`)"
      traefik.http.routers.app-sample.entrypoints: "websecure"
      traefik.http.routers.app-sample.tls.certresolver: "myresolver"
      traefik.http.services.app-sample.loadbalancer.server.port: "3000"

      traefik.http.services.app-sample.loadbalancer.healthcheck.path: "/healthcheck"
      traefik.http.services.app-sample.loadbalancer.healthcheck.port: "3000"
      traefik.http.services.app-sample.loadbalancer.healthcheck.interval: "3s"


networks:
  traefik:
    external: true